//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mothercare.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_comment
    {
        public int CommentId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Tbl_Members Tbl_Members { get; set; }
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
